site_name: TaskTide Documentation
site_description: Java Workflow Orchestration Engine for Data Application deployments
site_author: Brendan Kenna

site_url:  https://docs.tasktide.org
repo_url:  https://github.com/BrenKenna/TaskTide
repo_name: BrenKenna/TaskTide
edit_uri:  edit/main/
docs_dir:  .

theme:
  name: material
  
  favicon: assets/logo1.jpg
  logo: assets/logo1.jpg
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

  icon:
    repo: fontawesome/brands/github

  language: en

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search

nav:
  - 1). Home:                           index.md

  - 2). Guides:
    - a). Installation:                 Install.md
    - b). Database Configuration:       Database-Driver-Installation.md
    - c). Frequently Asked Questions:   FAQ.md

  - 3). Modules:
      - a). TaskTide:                   tasktide/README.md
      - b). Mutex:                      tasktide/mutex/README.md
      - c). Item Store:                 tasktide/itemstore/README.md
      - d). Core:                       tasktide/core/README.md
      - e). Engine:                     tasktide/engine/README.md
      - f). Web API:                    tasktide/api/README.md
      - g). Parser:                     tasktide/parser/README.md
      - h). Command-Line Client:        tasktide/tasktide/README.md

  - 4). Use Cases:
      - a). Introduction:               tasktide/use-cases/README.md
      - b). Workflows:                  tasktide/use-cases/workflow-use-case/README.md
      - c). Task Binding:               tasktide/use-cases/task-binding-use-case/README.md
      - d). AI Deployment:              tasktide/use-cases/deployment-use-case/README.md

  - 5). API Reference:
      - a). JavaDoc:                    https://api.docs.tasktide.org

  - 6). Changelog:
      - a). v1.0.0:                     https://github.com/BrenKenna/TaskTide/blob/main/CHANGELOG.adoc