##########################################################
##########################################################
## 
## 1). TaskTide Global Configurations
## 
##########################################################
##########################################################

# Which client to run
tasktide.client=manager


# Repository parameters
tasktide.core.repository.type=sql


# Utility parameters
tasktide.utils.date-format=dd/MM/yy HH:mm:ss
tasktide.utils.token-expiration-days=4


##########################################################
##########################################################
## 
## 2). TaskTide Manager Configurations
## 
##########################################################
##########################################################


# Collection Paramenters
tasktide.manager.inputFile=nestedTaskImports.txt
tasktide.manager.outputFile=results.txt
tasktide.manager.delimiter=|
tasktide.manager.nestedDelimiter=,
tasktide.manager.method=import
tasktide.manager.targetStep=myStep
tasktide.manager.target=WorkItem


##########################################################
##########################################################
## 
## 3). TaskTide Engine Configurations
## 
##########################################################
##########################################################


# Task Tide Engine Parameters
tasktide.engine.step=derp,myStep,berp
tasktide.engine.worker.lock-wait-time=4
tasktide.engine.worker.processor.threads.workitem=2
tasktide.engine.worker.processor.threshold.workitem=2

tasktide.engine.worker.processor.threads.itemtask=2
tasktide.engine.worker.processor.threshold.itemtask=2


# Time Keeper Observer
tasktide.engine.observer.timekeeper.level=1
tasktide.engine.observer.timekeeper.onStart.canFail=true
tasktide.engine.observer.timekeeper.onProcessing.canFail=true
tasktide.engine.observer.timekeeper.onPEnd.canFail=true
tasktide.engine.observer.timekeeper.waitTime=1000000


##########################################################
##########################################################
##  
## 5). JPA Config
##  
## References:
##  https://www.jetbrains.com/datagrip/jdbc-drivers/#
##  
##########################################################
##########################################################


# JDBC config: Must create database
datasource.url=jdbc:sqlserver://localhost:1433/tasktide_database
datasource.user=tasktide
datasource.password=password
datasource.driver=com.microsofot.sqlserver.jdbc.SQLServerDriver

hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
hibernate.hbm2ddl.auto=update