##########################################################
##########################################################
## 
## 1). TaskTide Global Configurations
## 
##########################################################
##########################################################


# Which client to run
tasktide.client=manager

# Repository parameters
tasktide.core.repository.type=rocksDB
tasktide.core.repository.file-path=/scratch/image-analysis/tasktide-rocskDB

#tasktide.core.repository.type=nosql
#tasktide.core.repository.jnosql.type=document

# Utility parameters
tasktide.utils.date-format=dd/MM/yy HH:mm:ss
tasktide.utils.token-expiration-days=4


##########################################################
##########################################################
## 
## 2). TaskTide Manager Configurations
## 
##########################################################
##########################################################


# Collection Paramenters
tasktide.manager.outputFile=results.txt
tasktide.manager.delimiter=|
tasktide.manager.method=import


##########################################################
##########################################################
## 
## 3). TaskTide Engine Configurations
## 
##########################################################
##########################################################


# Engine execution policy
tasktide.engine.execution-policy=batch


# Task Tide Engine Parameters
tasktide.engine.worker.lock-wait-time=4
tasktide.engine.worker.processor.threads.workitem=1
tasktide.engine.worker.processor.threshold.workitem=1

tasktide.engine.worker.processor.threads.itemtask=1
tasktide.engine.worker.processor.threshold.itemtask=1


# Time Keeper Observer
tasktide.engine.observer.timekeeper.level=1
tasktide.engine.observer.timekeeper.onStart.canFail=true
tasktide.engine.observer.timekeeper.onProcessing.canFail=true
tasktide.engine.observer.timekeeper.onPEnd.canFail=true
tasktide.engine.observer.timekeeper.waitTime=1000000


##########################################################
##########################################################
## 
## 4). Jakarta NoSQL 
## 
## Reference Configs GitHub:
##   jnosql-databases.git
##  
##########################################################
##########################################################


# Jakarta NoSQL config with CouchDB
#jnosql.document.provider=org.eclipse.jnosql.databases.couchdb.communication.CouchDBDocumentConfiguration
#jnosql.document.database=tasktide_database
#jnosql.couchdb.host=localhost
#jnosql.couchdb.username=admin
#jnosql.couchdb.password=password
#jnosql.couchdb.port=5984


# MongoDB
# jnosql.mongodb.host=localhost:27017
# jnosql.document.provider=org.eclipse.jnosql.databases.mongodb.communication.MongoDBDocumentConfiguration


##########################################################
##########################################################
##  
## 5). JPA Config
##  
## References:
##  https://www.jetbrains.com/datagrip/jdbc-drivers/#
##  
##########################################################
##########################################################


# JDBC config: Must create database
#datasource.url=jdbc:mysql://localhost:3306/tasktide_database
#datasource.user=admin
#datasource.password=password
#datasource.driver=com.mysql.cj.jdbc.Driver


# Hibernate config
#hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#hibernate.hbm2ddl.auto=update


##########################################################
##########################################################
## 
## 5). TaskTide REST-API 
## 
## https://eclipse-ee4j.github.io/jersey/
## https://jakarta.ee/specifications/restful-ws/
## 
##########################################################
##########################################################


# Base web service settings
#tasktide.web-api.host=http://localhost
#tasktide.web-api.port=8080
#tasktide.web-api.base-path=/tasktide